# Kõik vajalikud konstandid

HELEHALL = (100, 100, 100)

WIDTH = 1024
HEIGHT = 768
FPS = 60
TITLE = "Seiklus Deltasse"
BGCOLOR = HELEHALL

TILESIZE = 32
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

PLAYER_SPEED = 150
PLAYER_IMG = "player.png"
MURU_IMG = "muru.png"
POOSAS_IMG = "poosas.png"